[package]
name = "metaheuristicas"
version = "0.1.0"
authors = ["Asmilex <andresmm@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
nalgebra = "0.25.*"
multimap = "0.8.*"
csv = "1.*"
